services:
  - type: web
    name: unturned-inventory-db
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SECRET_TOKEN
        value: supersecretkey123
      - key: PORT
        value: 3000
