services:
  - type: web
    name: unturned-inventory-db
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SECRET_TOKEN
        value: supersecretkey123
      # Optionally set PROXY_URLS to a comma-separated list of proxy endpoints that accept a target URL appended or encoded.
      # Example (only if you have proxies): value: "https://myproxy.example.com/?u=,https://another-proxy/?url="
