services:
  - type: web
    name: unturned-inventory-db
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SECRET_TOKEN
        value: supersecretkey123
    autoDeploy: true
    regions:
      - oregon

staticPublishPath: public
